apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "youssefsapp.fullname" . }}-back
  labels:
    {{- include "youssefsapp.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: youssefsapp-back
      app.kubernetes.io/name: {{ include "youssefsapp.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        app: youssefsapp-back
        app.kubernetes.io/name: {{ include "youssefsapp.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: backend
    spec:
      imagePullSecrets:
{{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.service.port }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.backend.service.port }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "youssefsapp.fullname" . }}-back
spec:
  type: NodePort
  selector:
    app: {{ include "youssefsapp.name" . }}-back
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30081

