apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "youssefsapp.fullname" . }}-front
  labels:
    {{- include "youssefsapp.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.front.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "youssefsapp.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "youssefsapp.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: front
          image: "{{ .Values.front.image.repository }}:{{ .Values.front.image.tag }}"
          imagePullPolicy: {{ .Values.front.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.front.service.port }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.front.service.port }}
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.front.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "youssefsapp.fullname" . }}-front
  labels:
    {{- include "youssefsapp.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "youssefsapp.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.front.service.port }}

