frontend:
  image:
    repository: frontapp
    tag: local
    pullPolicy: Never
  service:
    name: frontend-service
    port: 80
  replicas: 1

backend:
  image:
    repository: backapp
    tag: local
    pullPolicy: Never
  service:
    name: backend-service
    port: 5000
  replicas: 1

ingress:
  enabled: true
  hosts:
    - host: myapp.local
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: frontend-service
              port:
                number: 80

